name: macOS/Ubuntu build philo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_build_philo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo
      run:  make re

  macos_build_philo:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo
      run:  make re
