name: macOS/Ubuntu compile check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_compile_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo
      run:  make re
      
  macos_compile_check:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo
      run:  make re
